# Generated by Django 4.2.7 on 2023-12-11 20:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
