# Generated by Django 4.2.7 on 2023-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0004_alter_ad_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
