# Generated by Django 4.2.7 on 2023-12-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0005_ad_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
