# Generated by Django 4.2.4 on 2023-08-14 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(choices=[('QL', 'Residential Lease'), ('QC', 'Commercial Lease'), ('ZH', 'Sales')], default='QL', max_length=2)),
                ('sub_area', models.CharField(choices=[('Airport', 'Airport'), ('North', 'North'), ('Central', 'Central'), ('South', 'South'), ('West', 'West')], max_length=15, null=True)),
                ('sub_min_price', models.IntegerField(default=0)),
                ('sub_max_price', models.IntegerField(null=True)),
                ('sub_min_bedrooms', models.IntegerField(default=0)),
                ('sub_max_bedrooms', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser_Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subscriptions')),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(through='users.CustomUser_Subscriptions', to='users.subscriptions'),
        ),
    ]
