# Generated by Django 4.2.4 on 2023-08-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscriptions_customuser_subscriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='sub_category',
            field=models.CharField(choices=[('QL', 'Residential Lease'), ('QC', 'Commercial Lease'), ('ZH', 'Property Sales')], default='QL', max_length=2, null=True),
        ),
    ]
