# Generated by Django 4.2.3 on 2023-07-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resproperties',
            name='area',
        ),
        migrations.AlterField(
            model_name='resproperties',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='resproperties',
            name='prop_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resproperties',
            name='prop_features',
            field=models.ManyToManyField(null=True, through='properties.PropertiesFeatures', to='properties.features'),
        ),
        migrations.AlterField(
            model_name='resproperties',
            name='status_valid',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
