# Generated by Django 4.2.3 on 2023-08-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_resproperties_area_alter_resproperties_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resproperties',
            name='prop_features',
            field=models.ManyToManyField(through='properties.PropertiesFeatures', to='properties.features'),
        ),
    ]
