# Generated by Django 4.2.3 on 2023-08-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_resproperties_prop_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resproperties',
            name='link',
        ),
    ]
