# Generated by Django 4.2.3 on 2023-08-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_resproperties_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resproperties',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
    ]
