# Generated by Django 4.2.4 on 2023-08-06 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contracts_closed', models.IntegerField(default=0, null=True)),
                ('revenue_generated', models.FloatField(default=0.0, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_1', models.CharField(max_length=15)),
                ('phone_2', models.CharField(max_length=15, null=True)),
                ('phone_3', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_feature', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_ql_id', models.CharField(max_length=10, unique=True)),
                ('activated', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_1', models.CharField(max_length=15)),
                ('phone_2', models.CharField(max_length=15, null=True)),
                ('phone_3', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents')),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.features')),
            ],
        ),
        migrations.CreateModel(
            name='ResProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.IntegerField(unique=True)),
                ('prop_division', models.CharField(choices=[('QL', 'Residential'), ('QC', 'Commercial'), ('ZH', 'Sales')], default='QL', max_length=2)),
                ('prop_type', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('address', models.TextField(null=True)),
                ('_price', models.FloatField(db_column='Price', default=0.0)),
                ('status', models.CharField(choices=[('RE', 'Rented'), ('AV', 'Available'), ('SO', 'Coming soon'), ('TC', 'To call')], default='RE', max_length=2)),
                ('status_valid', models.CharField(max_length=25, null=True)),
                ('off_the_market', models.BooleanField(default=False)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('prop_description', models.TextField(null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_rented', models.DateField(null=True)),
                ('date_expected', models.DateField(null=True)),
                ('time_updated', models.TimeField(auto_now=True)),
                ('lf', models.CharField(max_length=50, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.owners')),
                ('prop_features', models.ManyToManyField(through='properties.PropertiesFeatures', to='properties.features')),
            ],
        ),
        migrations.CreateModel(
            name='Viewings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.clients')),
                ('re_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties')),
            ],
        ),
        migrations.AddField(
            model_name='propertiesfeatures',
            name='re_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties'),
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField()),
                ('sign_date', models.DateField()),
                ('period', models.IntegerField(default=12)),
                ('final_price', models.FloatField(default=0.0)),
                ('af_paid', models.BooleanField(default=False)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('contract_signed', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.clients')),
                ('re_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents')),
                ('re_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties')),
            ],
        ),
    ]
