# Generated by Django 4.2.4 on 2023-11-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='added_by_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='comments',
            name='added_by_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='comments',
            name='added_by_ge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='comments',
            name='added_by_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='comments',
            name='added_on_en_us',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='added_on_es',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='added_on_ge',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='added_on_ru',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_ge',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='re_property_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties'),
        ),
        migrations.AddField(
            model_name='comments',
            name='re_property_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties'),
        ),
        migrations.AddField(
            model_name='comments',
            name='re_property_ge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties'),
        ),
        migrations.AddField(
            model_name='comments',
            name='re_property_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='af_paid_en_us',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracts',
            name='af_paid_es',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracts',
            name='af_paid_ge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracts',
            name='af_paid_ru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracts',
            name='agent_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='agent_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='agent_ge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='agent_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='client_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.clients'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='client_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.clients'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='client_ge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.clients'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='client_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.clients'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='contract_signed_en_us',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracts',
            name='contract_signed_es',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracts',
            name='contract_signed_ge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracts',
            name='contract_signed_ru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracts',
            name='deposit_paid_en_us',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracts',
            name='deposit_paid_es',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracts',
            name='deposit_paid_ge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracts',
            name='deposit_paid_ru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracts',
            name='final_price_en_us',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='final_price_es',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='final_price_ge',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='final_price_ru',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='move_in_date_en_us',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='move_in_date_es',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='move_in_date_ge',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='move_in_date_ru',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='period_en_us',
            field=models.IntegerField(default=12, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='period_es',
            field=models.IntegerField(default=12, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='period_ge',
            field=models.IntegerField(default=12, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='period_ru',
            field=models.IntegerField(default=12, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='re_property_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='re_property_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='re_property_ge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='re_property_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='sign_date_en_us',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='sign_date_es',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='sign_date_ge',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='sign_date_ru',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='prop_feature_en_us',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='features',
            name='prop_feature_es',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='features',
            name='prop_feature_ge',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='features',
            name='prop_feature_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='_price_en_us',
            field=models.FloatField(db_column='Price_en_us', default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='_price_es',
            field=models.FloatField(db_column='Price_es', default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='_price_ge',
            field=models.FloatField(db_column='Price_ge', default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='_price_ru',
            field=models.FloatField(db_column='Price_ru', default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='added_by_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='added_by_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='added_by_ge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='added_by_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='address_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='address_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='address_ge',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='address_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='bathrooms_en_us',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='bathrooms_es',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='bathrooms_ge',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='bathrooms_ru',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='bedrooms_en_us',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='bedrooms_es',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='bedrooms_ge',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='bedrooms_ru',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='date_added_en_us',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='date_added_es',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='date_added_ge',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='date_added_ru',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='date_expected_en_us',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='date_expected_es',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='date_expected_ge',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='date_expected_ru',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='lf_en_us',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='lf_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='lf_ge',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='lf_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='location_en_us',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='location_es',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='location_ge',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='location_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='off_the_market_en_us',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='off_the_market_es',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='off_the_market_ge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='off_the_market_ru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='owner_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.owners'),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='owner_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.owners'),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='owner_ge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.owners'),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='owner_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.owners'),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='prop_description_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='prop_description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='prop_description_ge',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='prop_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='prop_division_en_us',
            field=models.CharField(choices=[('QL', 'Residential'), ('QC', 'Commercial'), ('ZH', 'Sales')], default='QL', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='prop_division_es',
            field=models.CharField(choices=[('QL', 'Residential'), ('QC', 'Commercial'), ('ZH', 'Sales')], default='QL', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='prop_division_ge',
            field=models.CharField(choices=[('QL', 'Residential'), ('QC', 'Commercial'), ('ZH', 'Sales')], default='QL', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='prop_division_ru',
            field=models.CharField(choices=[('QL', 'Residential'), ('QC', 'Commercial'), ('ZH', 'Sales')], default='QL', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='prop_type_en_us',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='prop_type_es',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='prop_type_ge',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='prop_type_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='ref_en_us',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='ref_es',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='ref_ge',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='ref_ru',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='status_en_us',
            field=models.CharField(choices=[('RE', 'Rented'), ('AV', 'Available'), ('SO', 'Coming soon'), ('TC', 'To call')], default='RE', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='status_es',
            field=models.CharField(choices=[('RE', 'Rented'), ('AV', 'Available'), ('SO', 'Coming soon'), ('TC', 'To call')], default='RE', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='status_ge',
            field=models.CharField(choices=[('RE', 'Rented'), ('AV', 'Available'), ('SO', 'Coming soon'), ('TC', 'To call')], default='RE', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='status_ru',
            field=models.CharField(choices=[('RE', 'Rented'), ('AV', 'Available'), ('SO', 'Coming soon'), ('TC', 'To call')], default='RE', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='status_valid_en_us',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='status_valid_es',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='status_valid_ge',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='status_valid_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='time_updated_en_us',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='time_updated_es',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='time_updated_ge',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='resproperties',
            name='time_updated_ru',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='viewings',
            name='agent_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='viewings',
            name='agent_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='viewings',
            name='agent_ge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='viewings',
            name='agent_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agents'),
        ),
        migrations.AddField(
            model_name='viewings',
            name='client_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.clients'),
        ),
        migrations.AddField(
            model_name='viewings',
            name='client_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.clients'),
        ),
        migrations.AddField(
            model_name='viewings',
            name='client_ge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.clients'),
        ),
        migrations.AddField(
            model_name='viewings',
            name='client_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.clients'),
        ),
        migrations.AddField(
            model_name='viewings',
            name='date_en_us',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='viewings',
            name='date_es',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='viewings',
            name='date_ge',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='viewings',
            name='date_ru',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='viewings',
            name='re_property_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties'),
        ),
        migrations.AddField(
            model_name='viewings',
            name='re_property_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties'),
        ),
        migrations.AddField(
            model_name='viewings',
            name='re_property_ge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties'),
        ),
        migrations.AddField(
            model_name='viewings',
            name='re_property_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.resproperties'),
        ),
    ]
